From projector-idea-c
MAINTAINER haokaizhao

USER root
RUN apt-get update
RUN apt-get install g++ -y
RUN apt-get install gcc -y
RUN apt-get install gdb -y
RUN apt-get install cmake -y
RUN apt-get install git -y
RUN git config --global user.name "wuhuZhao"
RUN git config --global user.email hkzhao123@gmail.com
RUN echo "ok"



